---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - deactivate

install:
  - sudo pip install --upgrade ansible ansible-lint docker-py molecule pyOpenSSL
  - ansible --version
  - molecule --version

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
