---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  # - deactivate
  - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  # - sudo pip install --upgrade pip
  - pip install --upgrade ansible ansible-lint docker-py molecule pyOpenSSL Markdown cryptography PyYAML==3.12 six==1.11.0 requests
  - ansible --version
  - molecule --version

script:
  - ansible-lint -c .ansible-lint `find ./ -regex ".*\.\(yml\)"`
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
